### ISSUE TITLE
Initial datasets for site announcement

### ISSUE THREAD

**Issue by jvitello** [NuCivic/sldata#13]
Stefanie, how many datasets do you have ready to be uploaded when the site is stable again? I think ideally 2-3 per group would be a good starting place to make the site feel full, but there should at least be 1 in each group to justify a group's existence.

Currently:
Education - 0
Communications - 0
Demographics - 4
Food - 0
Aid - 0
Environment - 0
Transportation - 0
Business - 0
Energy - 0
Economics and Development - 0
Ebola - 0
Health - 0

**Comment by stefaniefgray** [comment]
Right now, I've got about 15 datasets on hand, ranging from Ebola data (mostly from https://data.hdx.rwlabs.org/ebola) to transportation to climate change. The final number will be bigger because the project's intern, David Adler, has been assigned to scour the web for more. 

He is specifically pulling in multiple datasets from http://www.statistics.sl as well as http://www.fao.org/countryprofiles/index/en/?iso3=SLE and http://www.unicef.org/infobycountry/sierraleone_statistics.html.

I agree that there should be at least one dataset per topic, if not 2-3 to make the site look and feel more comprehensive.

**Comment by jvitello** [comment]
Awesome work last night. The dataset groups look nicely fleshed out. I think that this is probably good enough for launch, so this should now be a low priority. Close this ticket when you feel you are totally done for the Saturday launch (can always add more later!)
