### ISSUE TITLE
Blog ownership should not display

### ISSUE THREAD

**Issue by jvitello** [NuCivic/sldata#16]
![blog_ownership](https://cloud.githubusercontent.com/assets/5174815/6857179/578db516-d3db-11e4-8862-148a324e3c22.png)

"Stefanie's blog" in the image above should not display. Stefanie said she could remove this.

**Comment by stefaniefgray** [comment]
Hmm, I thought that this was something I could fix within the main Drupal interface, but it turns out that I need access to the blog entry tpl.php to get rid of it:

http://drupal.stackexchange.com/questions/43840/hide-users-blog-link-on-blog-entries

It's a pretty easy fix of just copying and pasting this code, but I have no way to do this myself.

**Comment by drkloc** [comment]
http://live.data.sierraleone.nucivic.build/story/world-health-organization-western-area-surge-combats-ebola-proactively

done.
